### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
Many minor improvements to the README.

Edits through FAQ #68.

I'm having difficulty understanding FAQ #69.  I am not clear on what each color really means.  If you can provide more details and clarity for that item, it would be most useful!

### CODE REVIEW

**Comment by M66B** [comment]
Thank you very much again!

**Comment by M66B** [comment]
The color of FAQ 69 refers to the colored vertical bar in front of the applications.

grey is basically the default state, which turns into orange after most changes of the restrictions and which turns into green after submitting the restrictions to the crowd sourced restrictions server. This is to encourage sharing of restrictions settings.

**Comment by Gitoffthelawn** [comment]
You're welcome again... hopefully more to come!  :-)

And thank *you* again for XPrivacy.

Thanks also for the clarification of FAQ 69.  The gray makes sense, as does the green.

The orange might need a bit more clarification.  I've been experimenting to try to figure it out, and it appears that the orange is only assigned when a restriction is removed.  The orange does not seem to appear when a restriction is added.  It also does not appear for on demand restrictions being added or removed.  In conclusion, it appears that orange indicates "a regular (not on demand) restriction has been removed".  Is that by design, a bug, or an incorrect understanding?

**Comment by M66B** [comment]
Indeed there are some exceptions (which all have a history of discussions).

Basically it is what FAQ 69 says: *Orange: fetch, new/updated application, delete restrictions*

So, fetching from the crowd sourced restrictions, installing a new application, updating an existing application or deleting all restrictions for an application (which happens also when disabling restrictions in the main application list) will set the color to orange.

**Pull request merged**
