### PR TITLE
Compiled xPrivacy in Android Studio with Minor Changes

### PR DESCRIPTION
**Pull request by CircuitSerialKiller**
This is my first time ever publishing any source on GitHub and I don't have much idea what I'm doing at the moment. Please be kind and let me know what I did wrong:)
I know the changes I made to the notifyProgress method in UpdateService.java to work around the new rate limiting of notification updates in Android is just a quick hack, and the exact numbers may never be reached. Short of implementing some sort of internal notification rate tracking, perhaps the best idea is to eliminate the progress bar notification altogether. Thoughts?

### CODE REVIEW

**Comment by Cerberus-tm** [comment]
Wow, it's great that you're working on Xprivacy! I don't know if this is appropriate, but would it be an idea to explain here what kinds of things you changed besides this notification-update function?

**Comment by Cerberus-tm** [comment]
If it fixes problems on older versions of Android, why not merge it? Many people are still on Android 4.4. I wonder what the biggest problems are on Android 7 or 8, though, but I'll try to look that up myself.

**Comment by M66B** [comment]
It doesn't fix problems on older Android versions either, so I see no reason to merge this yet.

There is also the question about who is going to support an updated XPrivacy version.

**Comment by CircuitSerialKiller** [comment]
It's good to know there is at least one other person out there besides myself that's still of fan of XPrivacy and comprehends the amount of private and personal information and data that's being stolen from us and compiled together.
M66B is correct. There are zero fixes in this for the security restriction issues in XPrivacy on Android 6+. This is only to help me and anyone else that would hopefully like to continue on with this project where @M66B left off. I'm also a newbie to Android development, and am using this to help me learn and give me motivation. This is a lot for anyone to learn since it's not only understanding Android development, but also understanding the internals of the Android OS and how XPosed works as well, not to mention the GitHub workflow for collaborating with others.

**Comment by M66B** [comment]
@CircuitSerialKiller why not contribute to the XPrivacyLua project which was designed for and supported for Android 6 Marshmallow and later?

**Comment by M66B** [comment]
I think it is better to concentrate on [XPrivacyLua](https://github.com/M66B/XPrivacyLua/) only, so I am closing this pull request and archiving the XPrivacy project again. Pull requests to add things to XPrivacyLua are welcome, but better contact me first before starting to work on something.

**Pull request closed without merging**
