### PR TITLE
update and correct Simplified Chinese translation

### PR DESCRIPTION
**Pull request by shenm233**
I update again,because I can't stand these original translations.

### CODE REVIEW

**Comment by M66B** [comment]
I like to see this approved by someone else.

**Comment by shenm233** [comment]
@liudongmiao @wwj402  please review again.

**Comment by liudongmiao** [comment]
Some can be update, but other can be ignored.
So, I don't think the new translation is better than current.

@shenm233 I think it's better to let the original translator know.

**Comment by shenm233** [comment]
@liudongmiao which can be ignored?

**Pull request closed without merging**
