### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
Many more improvements!

Everything should be all good.

My only concern is that FAQ 69 is completely accurate.  Please verify accuracy of that item before accepting changes.  If I missed any cases for that item, please add them (or ask me to do so).

Enjoy!

### CODE REVIEW

**Comment by an0n981** [comment]
Grey is also when changing any restriction, not just onDemand

**Comment by Gitoffthelawn** [comment]
@an0n981 Thanks.  Based on your great feedback and that from @M66B, I updated FAQ 69.  It looks solid now.

**Comment by M66B** [comment]
Thanks again for your contributions!

**Comment by Gitoffthelawn** [comment]
You're quite welcome.  Glad to help.

Thank *you* for XPrivacy!

**Pull request merged**
