### PR TITLE
Samsung is misleading

### PR DESCRIPTION
**Pull request by an0n981**

### CODE REVIEW

**Comment by M66B** [comment]
I will never buy a Samsung device ;-)

**Comment by Cerberus-tm** [comment]
Hmm what has Samsung done this time? Are they trying to sneak around Android permissions or...?

**Comment by an0n981** [comment]
Look at the commit, it actually has nothing to do with Samsung

**Comment by Cerberus-tm** [comment]
I looked at the commit, but it seemed to be about the installation of Xposed?

**Comment by M66B** [comment]
The problem I have with Samsung is that they seem to have difficulties with open sourcing things each time, which hinders custom ROM development and also due to Samsung customizations Xposed development. For this reason I prefer to buy Nexus devices. These devices are supported for a long time (18 months and now even longer) and the software is almost always open source. I hope the stagefright security problem will help to get a better update policy in the Android world. It proves undeniable that this is a necessity.

**Comment by Cerberus-tm** [comment]
I couldn't agree more. Although luckily custom ROMs are usually available for the most popular phones. Wasn't there some Google project or initiative where manufacturers are only allowed to theme Android, not change the OS? I forgot the name, and I can't find it now.

**Pull request merged**
